### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by SpiderChat** [Devxoditas/radiobot#77]
After Create a .envrc file using example.envrc what next?

**Comment by ZeroDragon** [comment]
This bot is just a regular nodejs application
Just do 
```bash
npm install
```
Then 
```bash
node index.js
```

**Comment by SpiderChat** [comment]
radiobot@radio:~/radiobot$ node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/radiobot/radiobot/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
radiobot@radio:~/radiobot$

**Comment by ZeroDragon** [comment]
Index file is inside src directory. Use
```bash
node src/index.js
```

**Comment by SpiderChat** [comment]
> radiobot@radio:~/radiobot$ node src/index.js
> [INFO] XML Config file created
> [INFO] Getting PID
> (node:30286) UnhandledPromiseRejectionWarning: Error: 401: Bot Token is required
>     at Telegram.callApi (/home/radiobot/radiobot/node_modules/telegraf/lib/core/network/client.js:241:19)
>     at Telegram.getMe (/home/radiobot/radiobot/node_modules/telegraf/lib/telegram.js:12:21)
>     at Telegraf.launch (/home/radiobot/radiobot/node_modules/telegraf/lib/telegraf.js:100:98)
>     at Object.<anonymous> (/home/radiobot/radiobot/src/index.js:38:5)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>     at internal/main/run_main_module.js:17:47
> (node:30286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:30286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [INFO] No process currently running
> [INFO] Getting PID
> events.js:291
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn ezstream ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
>     at onErrorNT (internal/child_process.js:470:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
>     at onErrorNT (internal/child_process.js:470:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn ezstream',
>   path: 'ezstream',
>   spawnargs: [ '-c', '/home/radiobot/radiobot/ezstream-conf.xml' ]
> }
> radiobot@radio:~/radiobot$
> 

Need to install ezstream? Any things else?

**Comment by k001** [comment]
not an issue from here
